### ISSUE TITLE
Color output

### ISSUE THREAD

**Issue by xr09** [leiserfg/lic#1]
The blue is hard to read on my terminal, a green perhaps?

![blue](http://s18.postimg.org/3ygij1fxl/image.jpg)

vs

![green](http://s10.postimg.org/631gwadmh/image.jpg)

Nice tool, comes handy.

**Comment by leiserfg** [comment]
Imagine that your terminal had a green palette (Linux palette), you will not see green text, I think a good color for that will be the same `ls` use  for directories:
`dircolors -p|grep DIR`
in my  own case (the default case):
`DIR 01;34 # directory`
it's is the blue color of the pallet (and also works on every konsole default configuration)

**Comment by xr09** [comment]
Yep, disabling transparency solves this. I have issues with colors, always tweaking.
